version: "3.8"
services:
  mongo-db:
    image: mongo:6.0.2
    container_name: mongo-db
    volumes:
      - mongo-db:/data/db
      - mongo-db-config:/data/configdb
    ports:
      - "27017:27017"
  log-service-1:
    image: jbenitezg/aygo1-log-service:1.0
    container_name: log-service-1
    ports:
      - "6001:6001"
    environment:
      - PORT=6001
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
    depends_on:
      - mongo-db
  log-service-2:
    image: jbenitezg/aygo1-log-service:1.0
    container_name: log-service-2
    ports:
      - "6002:6002"
    environment:
      - PORT=6002
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
    depends_on:
      - mongo-db
  log-service-3:
    image: jbenitezg/aygo1-log-service:1.0
    container_name: log-service-3
    ports:
      - "6003:6003"
    environment:
      - PORT=6003
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
    depends_on:
      - mongo-db
  load-balancer-app:
    image: jbenitezg/aygo1-lb-app:1.0
    container_name: load-balancer-app
    ports:
      - "80:6000"
    environment:
      - PORT=6000
      - SERVERS=http://log-service-1:6001,http://log-service-2:6002,http://log-service-3:6003
    depends_on:
      - log-service-1
      - log-service-2
      - log-service-3

volumes:
  mongo-db: { }
  mongo-db-config: { }
